### ISSUE TITLE
Probelmas nos background.

### ISSUE THREAD

**Issue by tomast1337** [suzanadossantos/landing-page#1]
# Nessas duas paginas o background não se encaixa a pagina.

### Balle Bot
![image](https://user-images.githubusercontent.com/15125899/219967156-e482775e-dfe0-4c27-90d7-e7bd894e2b01.png)
### Blog - Suzana dos Santos
![image](https://user-images.githubusercontent.com/15125899/219967180-62f56054-257f-4e77-9b22-2fc09bc2085f.png)

Proponho mudar o css da seguinte maneira:

### Balle Bot
```diff
+ html {
+     min-height:100%;
+ }

 body{
     font-size: 100%;
+    background-image: linear-gradient(68.15deg, #2F2325 16.62%, #8E5D52 85.61%);
+    background-repeat: no-repeat;
+    background-size: cover;
+    background-position: center;
+}
```
### Blog - Suzana dos Santos

```diff
+html {
+    min-height:100%;
+}
```

Assim as paginas ficaram assim:

### Balle Bot
![image](https://user-images.githubusercontent.com/15125899/219967429-93f14149-27cf-464a-8f1d-4a98b71b2ec8.png)

### Blog - Suzana dos Santos
![image](https://user-images.githubusercontent.com/15125899/219967492-e0043497-ae68-45b9-84de-a099fdee3339.png)

Fiz um PR com as alterações.

**Comment by suzanadossantos** [comment]
Obrigada pelas dicas!

**Comment by suzanadossantos** [comment]
Obrigada pelas dicas!
